/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppHistoricoRouteImport } from './routes/_app.historico'
import { Route as AppFeiraRouteImport } from './routes/_app.feira'
import { Route as AppEstoqueRouteImport } from './routes/_app.estoque'
import { Route as AppComprasRouteImport } from './routes/_app.compras'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppFeiraRoute = AppFeiraRouteImport.update({
  id: '/feira',
  path: '/feira',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/unlock': typeof UnlockRoute
  '/compras': typeof AppComprasRoute
  '/estoque': typeof AppEstoqueRoute
  '/feira': typeof AppFeiraRoute
  '/historico': typeof AppHistoricoRoute
}
export interface FileRoutesByTo {
  '/unlock': typeof UnlockRoute
  '/compras': typeof AppComprasRoute
  '/estoque': typeof AppEstoqueRoute
  '/feira': typeof AppFeiraRoute
  '/historico': typeof AppHistoricoRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_app/compras': typeof AppComprasRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/feira': typeof AppFeiraRoute
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/unlock' | '/compras' | '/estoque' | '/feira' | '/historico'
  fileRoutesByTo: FileRoutesByTo
  to: '/unlock' | '/compras' | '/estoque' | '/feira' | '/historico' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/unlock'
    | '/_app/compras'
    | '/_app/estoque'
    | '/_app/feira'
    | '/_app/historico'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feira': {
      id: '/_app/feira'
      path: '/feira'
      fullPath: '/feira'
      preLoaderRoute: typeof AppFeiraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compras': {
      id: '/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppComprasRoute: typeof AppComprasRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFeiraRoute: typeof AppFeiraRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComprasRoute: AppComprasRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFeiraRoute: AppFeiraRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
