/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRefeicoesRouteImport } from './routes/_app.refeicoes'
import { Route as AppMercadosRouteImport } from './routes/_app.mercados'
import { Route as AppHistoricoRouteImport } from './routes/_app.historico'
import { Route as AppFeiraRouteImport } from './routes/_app.feira'
import { Route as AppEstoqueRouteImport } from './routes/_app.estoque'
import { Route as AppComprasRouteImport } from './routes/_app.compras'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRefeicoesRoute = AppRefeicoesRouteImport.update({
  id: '/refeicoes',
  path: '/refeicoes',
  getParentRoute: () => AppRoute,
} as any)
const AppMercadosRoute = AppMercadosRouteImport.update({
  id: '/mercados',
  path: '/mercados',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppFeiraRoute = AppFeiraRouteImport.update({
  id: '/feira',
  path: '/feira',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/unlock': typeof UnlockRoute
  '/compras': typeof AppComprasRoute
  '/estoque': typeof AppEstoqueRoute
  '/feira': typeof AppFeiraRoute
  '/historico': typeof AppHistoricoRoute
  '/mercados': typeof AppMercadosRoute
  '/refeicoes': typeof AppRefeicoesRoute
}
export interface FileRoutesByTo {
  '/unlock': typeof UnlockRoute
  '/compras': typeof AppComprasRoute
  '/estoque': typeof AppEstoqueRoute
  '/feira': typeof AppFeiraRoute
  '/historico': typeof AppHistoricoRoute
  '/mercados': typeof AppMercadosRoute
  '/refeicoes': typeof AppRefeicoesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_app/compras': typeof AppComprasRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/feira': typeof AppFeiraRoute
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/mercados': typeof AppMercadosRoute
  '/_app/refeicoes': typeof AppRefeicoesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unlock'
    | '/compras'
    | '/estoque'
    | '/feira'
    | '/historico'
    | '/mercados'
    | '/refeicoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unlock'
    | '/compras'
    | '/estoque'
    | '/feira'
    | '/historico'
    | '/mercados'
    | '/refeicoes'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/unlock'
    | '/_app/compras'
    | '/_app/estoque'
    | '/_app/feira'
    | '/_app/historico'
    | '/_app/mercados'
    | '/_app/refeicoes'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/refeicoes': {
      id: '/_app/refeicoes'
      path: '/refeicoes'
      fullPath: '/refeicoes'
      preLoaderRoute: typeof AppRefeicoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mercados': {
      id: '/_app/mercados'
      path: '/mercados'
      fullPath: '/mercados'
      preLoaderRoute: typeof AppMercadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feira': {
      id: '/_app/feira'
      path: '/feira'
      fullPath: '/feira'
      preLoaderRoute: typeof AppFeiraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compras': {
      id: '/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppComprasRoute: typeof AppComprasRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFeiraRoute: typeof AppFeiraRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppMercadosRoute: typeof AppMercadosRoute
  AppRefeicoesRoute: typeof AppRefeicoesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComprasRoute: AppComprasRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFeiraRoute: AppFeiraRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppMercadosRoute: AppMercadosRoute,
  AppRefeicoesRoute: AppRefeicoesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
